version: '3.8'

services:
  api-server:
    image: ghcr.io/ericafenyo/care-hub-api:${GIT_COMMIT_HASH:-latest}

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

    environment:
      - SPRING_PROFILES_ACTIVE=docker-stack
      - SPRING_CONFIG_IMPORT=optional:configtree:/run/secrets/

    secrets:
      - datasource_url
      - datasource_username
      - datasource_password
    ports:
      - "8080:8080"
    networks:
      - app-network
secrets:
  datasource_url:
    external: true
  datasource_username:
    external: true
  datasource_password:
    external: true

networks:
  app-network:
    driver: overlay