services:
  db:
    image: mysql:8.4.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: senior_hub

  smtp:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"