name: "Build & Push Docker Image to GHCR"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build the JAR file
        run: ./mvnw clean package -DskipTests

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.ACCESS_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.actor }}/care-hub-api:latest .

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.actor }}/care-hub-api:latest
