name: "CI/CD"

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Generate application.properties.tmpl
        run: |
          sed 's|spring.datasource.url=.*|spring.datasource.url={{ secret \"datasource_url\" }}|' application.properties > application.properties.tmpl
          sed -i 's|spring.datasource.username=.*|spring.datasource.username={{ secret \"datasource_username\" }}|' application.properties.tmpl
          sed -i 's|spring.datasource.password=.*|spring.datasource.password={{ secret \"datasource_password\" }}|' application.properties.tmpl

      - name: Build the JAR file
        run: ./mvnw clean package -DskipTests

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Build and push the Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/care-hub-api:latest
            ghcr.io/${{ github.actor }}/care-hub-api:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-image
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Create and use docker context for remote server
        run: |
          docker context create deploy --docker "host=ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}"
          docker context use deploy

        #      - name: Login to GitHub Container Registry
        #        uses: docker/login-action@v3
        #        with:
        #          registry: ghcr.io
        #          username: ${{ github.actor }}
        #          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Deploy to remote server swarm
        with:

        run: |
          docker stack deploy -c deploy-compose.yml care-hub-api-stack